version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - epub
  # FIXME: latex failure
  # - pdf

build:
  os: "ubuntu-22.04"
  apt_packages:
    - pandoc
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - rm -rf docs/source/api
      - sphinx-apidoc
        --private
        --module-first
        --force
        --output-dir docs/source/api
        src/pygama
        src/pygama/_version.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
