codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        informational: true
    patch: false

github_checks:
    annotations: false

comment:
  require_changes: true

ignore:
  - tests
  - docs
